# Permalinks
permalink:           pretty

# Setup
title:               ISE Research Group
tagline:             
url:                 http://ISE-FIZKarlsruhe.github.io
baseurl:             /progress-for-jekyll
analytics_id:

# Owner/author information
owner:
  name:           
  avatar:         
  bio:            
  email:          
  twitter:        
  github:         
  instagram:      
  dribbble:       
  location:       "Karlsruhe, DE"


# Custom vars
version:             2.0.0
github:
  repo:              

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
